apiVersion: apps/v1
kind: Deployment
metadata:
  name: pasite-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pasite-dev
  template:
    metadata:
      name: pasite-dev
      namespace: dev
      labels:
        app: pasite-dev
    spec:
      securityContext:
        runAsUser: 1000 
        runAsNonRoot: true
        runAsGroup: 1000
        fsGroup: 1000
      nodeSelector:
        eks.amazonaws.com/nodegroup: dev
      containers:
        - name: pasite-dev
          image: 367893350766.dkr.ecr.ap-southeast-1.amazonaws.com/pasite-dev:0.0.159
          ports:
            - name: http
              containerPort: 7070
          env:
            - name: NODE_ENV
              value: 'development'
          

