name: deploy dev

on:
  push:
    branches: [ dev ]

jobs:
  call_jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - if: "!contains(github.event.head_commit.message, 'skip github action')"
        name: jenkins
        run: |
          curl POST 'http://jenkins.paathena.co.kr/buildByToken/buildWithParameters?job=pasite-dev&token=112386fb9cb04d4b1b7af7ed444dc325d5&branch=${{ steps.extract_branch.outputs.branch }}&author=${{ github.actor }}'
